import AccountCircleIcon from '@mui/icons-material/AccountCircle';
import FactoryIcon from '@mui/icons-material/Factory';
import FileDownloadIcon from '@mui/icons-material/FileDownload';
import FormatAlignLeftIcon from '@mui/icons-material/FormatAlignLeft';
import PlaylistPlayIcon from '@mui/icons-material/PlaylistPlay';
import SettingsIcon from '@mui/icons-material/Settings';
import TimerOutlinedIcon from '@mui/icons-material/TimerOutlined';

const tiles = [
  {
    id: 1,
    title: 'PlantArea',
    home: '/',
    category: 'Menu',
    icon: <FactoryIcon style={{ fontSize: '100px' }} />,
    target: 'plantarea',
  },
  {
    id: 2,
    title: 'Rules',
    home: '/',
    category: 'Menu',
    icon: <SettingsIcon style={{ fontSize: '100px' }} />,
    target: '/rules',
  },
  {
    id: 3,
    title: 'Program',
    home: '/',
    category: 'Menu',
    icon: <FormatAlignLeftIcon style={{ fontSize: '100px' }} />,
    target: '/program',
  },
  {
    id: 4,
    title: 'DLZParameterization',
    home: '/',
    category: 'Menu',
    icon: <TimerOutlinedIcon style={{ fontSize: '100px' }} />,
    target: '/dlzparameterization',
  },
  {
    id: 5,
    title: 'SimulateResult',
    home: '/',
    category: 'Functions',
    icon: <PlaylistPlayIcon style={{ fontSize: '100px' }} />,
    target: '/simulateresult',
  },
  {
    id: 6,
    title: 'FileDownload',
    home: '/',
    category: 'Functions',
    icon: <FileDownloadIcon style={{ fontSize: '100px' }} />,
    target: '/filedownload',
  },
  {
    id: 7,
    title: 'Permissions',
    home: '/',
    category: 'Administration',
    icon: <AccountCircleIcon style={{ fontSize: '100px' }} />,
    target: '/permissions',
  },
  {
    id: 8,
    title: 'Sections',
    home: '/plantarea',
    category: 'PlantArea',
    icon: null,
    target: '/plantarea/sections',
  },
  {
    id: 9,
    title: 'Lines',
    home: '/plantarea',
    category: 'PlantArea',
    icon: null,
    target: '/plantarea/lines',
  },
  {
    id: 10,
    title: 'Shifts',
    home: '/plantarea',
    category: 'PlantArea',
    icon: null,
    target: '/plantarea/shifts',
  },
  {
    id: 11,
    title: 'WorkingHours',
    home: '/plantarea',
    category: 'PlantArea',
    icon: null,
    target: '/plantarea/worktime',
  },
  {
    id: 12,
    title: 'CTBackpacks',
    home: '/rules',
    category: 'Rules',
    icon: null,
    target: '/rules/ctbackpacks',
  },
  {
    id: 13,
    title: 'VehicleClasses',
    home: '/rules',
    category: 'Rules',
    icon: null,
    target: '/rules/vehicleclasses',
  },
  {
    id: 14,
    title: 'VehicleRules',
    home: '/rules',
    category: 'Rules',
    icon: null,
    target: '/rules/vehiclerules',
  },
  {
    id: 15,
    title: 'Densities',
    home: '/rules',
    category: 'Rules',
    icon: null,
    target: '/rules/densities',
  },
  {
    id: 16,
    title: 'Capacities',
    home: '/program',
    category: 'Program',
    icon: null,
    target: '/program/capacities',
  },
  {
    id: 17,
    title: 'Distributions',
    home: '/program',
    category: 'Program',
    icon: null,
    target: '/program/distributions',
  },
  {
    id: 18,
    title: 'AuditCapacities',
    home: '/dlzparameterization',
    category: 'DlzParameterization',
    icon: null,
    target: '/dlzparameterization/auditcapacities',
  },
  {
    id: 19,
    title: 'Roles',
    home: '/permissions',
    category: 'Permissions',
    icon: null,
    target: '/permissions/roles',
  },
  {
    id: 20,
    title: 'Users',
    home: '/permissions',
    category: 'Permissions',
    icon: null,
    target: '/permissions/users',
  },
];

export default tiles;
